### DISCUSSION TITLE
Workaround with Github Actions and Concord

### DISCUSSION THREAD

**Discussion by transgirllucy** [Cogmasters/concord#119] [Ideas]
```yaml
name: Concord Compiling

on:
  push:
    [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cloning Concord from Github
        run: git clone https://github.com/Cogmasters/concord.git && cd
      
      - name: Installing dependencies
        run: apt update && apt install -y libcurl4-openssl-dev gcc

      - name: Compiling Concord
        run: make -j$(nproc) && sudo make install
      
      - name: Compiling Project
        run: cd ~ && gcc main.c -pthread -ldiscord -lcurl
```
